name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: gcc
      run: gcc
    - name: -g
      run: -g
    - name: file
      run: 0000970373.c
    - name: obj
      run: -o
    - name: main
      run: -o

    - name: run
      run: ./main
    - name: par
      run: test3.in
